### ISSUE TITLE
Finalize Ines' Loan Parameters and Amortization Table

### ISSUE THREAD

**Issue by onggunhao** [onggunhao/enable#10]
* I will be using Apache Fineract (an open source core banking system) to illustrate key loan concepts, as well as generate a sample amortization table.

**Mifos Demo:**
[demo.fiter.io](https://demo.fiter.io)
User: `mifos`
Pass: `password`

### Sample Loan Parameters
See annotated screenshots below

![image](https://user-images.githubusercontent.com/518024/56459119-c830f380-63c1-11e9-865b-6fca7a19de6a.png)

### Sample Fee Parameters

![image](https://user-images.githubusercontent.com/518024/56459387-62466b00-63c5-11e9-8fa6-104a9cd4ec8b.png)

### Sample Amortization Table

Bear in mind that this amortization table is at a 3% per month interest (i.e. 36% per year), which wreaks havoc on the numbers (you'll see that a $60k loan eventually earns the bank 3 times that amount in interest!) This is the reality facing emerging markets

![image](https://user-images.githubusercontent.com/518024/56459427-1d6f0400-63c6-11e9-8d73-b6762891d642.png)

![image](https://user-images.githubusercontent.com/518024/56459488-f107b780-63c6-11e9-900b-e12a69a704c5.png)

### Realistic do-up of sample loan:

I used Apache Fineract below, and then go to the following URL
[demo.fiter.io](https://demo.fiter.io)
User: `mifos`
Pass: `password`

https://demo.fiter.io/#/viewloanaccount/126

**Parameters**
Principal: US$60,000
Interest: 6% per annum (i.e. 0.5% monthly)
Grace period on Principal: 24 months
Loan Tenor: 144 months (12 years including 2 years of study)

**Results**
Grace period installment (1st 2 years): $295-305
Monthly installment post-graduation: $700
Final repayment tranche: 20 Sept 2030

**Comment by tspoff** [comment]
Very cool, this helps put things in perspective.

My current line of thinking is that we pre-calculate the amount owed each month and have the terms contract use that. When someone calls expectedRepaidAmount(), it will determine how long it's been and look up the total that should have been repaid at that time.

As the payments are based on months, we’ll just have a double-digit number of entries and the timestamp precision won’t be an issue (Good enough for crowdsales good enough for us)

**Comment by wimanesti** [comment]
**Parameters**
Principal: US$60,000
Interest: 6% per annum (i.e. 0.5% monthly)
Grace period on Principal: 24 months
Loan Tenor: 120 months (10 years including 2 years of study)

Results
Grace period installment (1st 2 years): $300
Monthly installment post-graduation: $800
Final repayment tranche: 20 Sept 2029

**Comment by adibas03** [comment]
@tspoff I think the Repayment system in the contracts already handle this pretty well. The only difference is that we do not pre-calculate the amount, but  rather do a spot calculation when the repayment is to be made.
The only aspects yet to be accounted for a re interests and low-fees,
so in it present state, the contract bills 0% interest and No late fees.

**Comment by onggunhao** [comment]
Closing this issue as @wimanesti has confirmed loan terms
