### ISSUE TITLE
Do up first iteration of wireframes for Lender's view (fractional funding), Social Attestation, Repayment tracking

### ISSUE THREAD

**Issue by onggunhao** [onggunhao/enable#13]

**Comment by onggunhao** [comment]
Initial quick wireframes of homepage (inspired by Instadapp's clean design)

![Homepage](https://user-images.githubusercontent.com/518024/56603855-ce75d880-662a-11e9-879f-625efb1a830f.png)

**Comment by onggunhao** [comment]
Quick 2nd iteration (cc @tspoff @wimanesti)

![Homepage](https://user-images.githubusercontent.com/518024/56605226-d6834780-662d-11e9-92dd-8b01448e305c.png)

**Comment by nczhu** [comment]
Dis is amazing

**Comment by onggunhao** [comment]
Loan Request Page

cc @tspoff @wimanesti @adibas03

![image](https://user-images.githubusercontent.com/518024/56687262-1286dd00-6700-11e9-9bc2-ab5356f0917a.png)

**Comment by adibas03** [comment]
@onggunhao Since a user can only have one loan at a time, would it be of any UX advantage, to have the loan address somewhere in there?
