### ISSUE TITLE
Architecture Discussion

### ISSUE THREAD

**Issue by tspoff** [onggunhao/enable#20]
Here's a link to a draw.io architecture diagram (can open in draw.io and make changes I believe)
https://drive.google.com/file/d/1U54sHhv3xVk7-CZ5dnR1l-UjgkhmGyRO/view?usp=sharing

I'm happy to recreate it in a more collab-friendly software if anyone has suggestions.

**Comment by adibas03** [comment]
Architecture looks good so far,
I do have some concerns about the flow:  

- Handle bloom user account: Thoughts on Public/private attestation. Also, I believe reputations should be more than just number of attestaion (Maybe future versions will handle this), except if all attestations are public and the accounts making the attestations are public as well.
- IPFS verification: we need to confirm that the content on Ipfs is same as that provided to contract: (IPFS hash)

**Comment by onggunhao** [comment]
I think we should make sure that it's do-able within the hackathon parameters (i.e. this looks like a pretty long roadmap). Probably might need to oversimplify a lot of things

I think a non-trivial aspect of it is actually the business use case - @wimanesti and I are spending quite a bit of extra time making sure that this is legally above board, and speaking w/ her and her family about the responsibilities of the loan

**Comment by adibas03** [comment]
@onggunhao Yeah, the simplest possible version is the target.I think we have about 5 days left
