### ISSUE TITLE
Loan Funding page

### ISSUE THREAD

**Issue by adibas03** [onggunhao/enable#23]
- [x] Profile pic of Ines with heading
- [x] Description of loan
- [x] Loan attestation box
- [x] Verified identity box
- [x] Funding box (crowdfunding)
- [x] Progress box

@tspoff  
I am starting to implement the Mockups from @onggunhao in #13  .
Is there a particular preference for `rebass` https://rebassjs.org/getting-started,
We will need something with more components.
I am thinking we could use this to test https://rimble.consensys.design/

**Comment by tspoff** [comment]
I'm open to whatever component libraries people want to use. I started using shards-react and that landing page components set.

**Comment by onggunhao** [comment]
Similar - I think Rimble comes with some.nice stuff out of the box. The Sketch wireframes we're actually done using the React Shards sketch template but tbh I think whatever we are fastest w/ working is best

**Comment by adibas03** [comment]
@onggunhao @tspoff Just looking through `shards-react`. It is definitely a more complete suite than `rimble`. We should retain it, and use `rimble` for `ethereum` specific components, not available in shards.
I should have the landing page complete before closing in for the day, today...Hopefully.

**Comment by onggunhao** [comment]
Awesome stuff @adibas03!

**Comment by onggunhao** [comment]
@adibas03 I'll be picking this one up again
