### ISSUE TITLE
Demo Discussion

### ISSUE THREAD

**Issue by tspoff** [onggunhao/enable#26]
The MVP live demo imo is a lender signing on, checking out the homepage / loan / user profile, and requesting data from the user. 
I'm using Ines (Borrower) and Daniel (Lender) as the sample users here.

### Build Process
- Deploy our smart contracts to rinkeby or mainnet
- Deploy the web app on Heroku

### Pre-demo setup
- Ines creates the Loan request
- Daniel vouches for Ines account.

### Demo 
- Daniel signs in and views the landing page / loan page / account page.
- Asks for attestation data from Ines to evaluate candiate?
- Ines forward their attestation data from Bloom to the potential lender somehow.
- Daniel makes a payment to the (rinkeby) crowdsale and it shows in UI.

Any more steps we can add to the UI are good:
- Creating loan requests through the UI.
- Stake other users through the UI.
- Display full repayment data like in the mockups.

More important than any by far is a well researched business case imo

#### Consideration: Data that currently isn't stored anywhere
Large text (user public profile, loan description): We can just mock it up in the front-end, or store on IPFS if there is time.
User photo: Likewise.

**Comment by onggunhao** [comment]
1. For demo, let's just do Rinkeby

2. For "asks for attestation data", can we instead use something simple (eg schedule video interview w Ines). We could do something cool w encrypted data using requester's public key on IPFS but I don't think it's feasible within scope of time 

3. Data that isn't stored anywhere - we can just hard code for now (only 1 loan available)
