### ISSUE TITLE
Add an email opt-in on landing page

### ISSUE THREAD

**Issue by tspoff** [onggunhao/enable#29]
This is a plus for the bounty judgers, to have a live site with an email opt-in.

**Comment by adibas03** [comment]
@onggunhao Implemented a draft opt-in component. Can you update with an optimized component
![image](https://user-images.githubusercontent.com/6083241/56872752-55102880-6a24-11e9-9598-be7f8ab027cc.png)

**Comment by adibas03** [comment]
![image](https://user-images.githubusercontent.com/6083241/56872776-96a0d380-6a24-11e9-86d7-f5dfa6eb341f.png)

**Comment by adibas03** [comment]
@tspoff Did you implement the back-end for the Email opt-in ?
