### ISSUE TITLE
Assess Stablecoin suitability (Dai, USDC, Paxos etc) as a fundraising medium and smart-contract compatibility

### ISSUE THREAD

**Issue by onggunhao** [onggunhao/enable#6]
### Why
* Dai might be too volatile and high stability fees might result in very high interest rates (currently 14.5%). For 150% collateralized loans on Dharma, the interest rate is 11%.

* Dai currently only trades at ~0.98 : 1 USD. The exchange rate still fluctuating and there is a chance that it changes in the future, leaving Ines susceptible to forex risk.

* Fiat-based stablecoins might have significantly lower interest rates.

**Comment by tspoff** [comment]
While Dai is really cool, I'd be partial to the stablecoins from regulated financial institutions in this case (which I believe the other two are)

The fluctuation potential in Dai could be disastrous for a long term loan.
