### ISSUE TITLE
Check viability of Compound for loans

### ISSUE THREAD

**Issue by tspoff** [onggunhao/enable#63]
* After talking with the founder, I've learned Compound is interested in companies building on top of their platform. I'll see if / how we can use the platform.
* I'd prefer to minimize the custom smart contracts for risk and expense

**Comment by onggunhao** [comment]
Looking over the [Compound API](https://compound.finance/developers#borrow-function):

* Current [`Borrow` API](https://compound.finance/developers#borrow-function) seems to only be for single-tranche loans
* Interest accumulates at Compound's interest rate (we cannot specify)
* Collateral required (using Compound's contract)

Not sure if this is immediately applicable to Ines' situation
