### ISSUE TITLE
Test assumption that people are willing to loan Ines stablecoins at prevailing rate (6%)

### ISSUE THREAD

**Issue by onggunhao** [onggunhao/enable#74]
# Task

1. We need to **test and validate the assumption** that there are at least 600 people willing to give a $100 stablecoin loan.

# Why this is important

Enable is a P2P marketplace. We've validated demand for one side (i.e. demand for loans). I don't think we've validated demand for the other side (i.e. supply of loans). It's critical to validate this for the following reasons:

- Ines needs to have some idea of whether she needs to find alternatives

- The time cost of building even a MVP is high, and there is opportunity cost on our part

- This is especially for the design / front-end eng part, which is time consuming

I learned a few hard lessons from previous startups: 

- Always do a demand experiment before sinking in time / resources (i.e. Tim Feriss)

- Do riskiest assumption tests, instead of building MVPs: i.e. test core value prop before getting stuck in product / eng

# Proposal

I'll use 2hrs to do up a simple one page site at [www.ines.fund](www.ines.fund). This one page site will articulate the lender value proposition. It'll include the interest rate, repayment schedule, our backstory at the hackathon

We'll then have a simple call to action that leads to a Google Form. We'll ask:
-------

- Do they want to lend or do they want to donate?
- How much are they willing to lend? 
- What interest rate do they want to lend at?
- What stablecoin do they want to lend in?
- Do they mind having a video interview w Ines as a pre-screen?
- What recourse do they want in case of late payments or defaults?

-------

This data is important for us to figure out whether this project looks more like a GoFundMe, Kiva, or LendingClub.

I'll put this out on Crypto Twitter and Reddit etc, and we'll ask the community to help us forward it around. Hopefully Consensys will help us spread the survey.

I see this as a low-risk experiment which helps us learn quickly and fail fast. 

If the results come back negative, I still think I'll work on the project but really focus on the Solidity stuff instead of trying to fill the gaps on design/UX and "bizdev".

**Comment by tspoff** [comment]
Nice post. I'll see if the Consensys Labs people have any thoughts tomorrow.

My first question is what returns are already available for stablecoin loans? 
And crypto loans in general?

Dharma is advertising 8% interest for collateralized USDC loans and 14% for DAI
Compound 9.38% for DAI

**Comment by vs77bb** [comment]
@onggunhao If I received a 7-10% return, $100 would be a small price to pay to also be a part to getting Ines towards her dream school. 

This is helped by the fact that I now feel personally invested in her story after seeing the Enable submission and what you folks were able to build in the hackathon. Telling that story likely helps in getting others involved, especially as we think about social credit as the main backer of her here. 

That being said, it's probably worth outlining the risks to a lender. I don't feel like I'm making a financial decision here as much as a social one... but it does feel like the financial return invests me in her success more than a $100 donation would.

**Comment by onggunhao** [comment]
Cool - I've created a simple Google Form with the relevant questions. You can see it here:
http://bit.ly/enable-survey

I'll be testing the assumption by posting at the following avenues:

- [ ] MakerDAO Rocketchat
- [ ] USDC ?
- [ ] Bloom Telegram
- [ ] r/cryptocurrencies
- [ ] r/blockchain
- [ ] r/ethereum and r/ethtrader
- [ ] r/usdc
- [ ] r/makerdao
- [ ] Crypto Twitter (help me retweet!)

**Comment by adibas03** [comment]
@onggunhao You should also add the links to the posts on reddit and twitter, on this issue.
So, whoever finds themselves here can also help spread the word

**Comment by onggunhao** [comment]
# Results

We received 100+ votes on Twitter, and 21 responses on Google Forms. I was an idiot and accidentally deleted all my tweets, but managed to salvage the results through a cached browser tab.

## Q1: Would you lend stablecoins to borrowers in emerging markets

![image](https://user-images.githubusercontent.com/518024/58418151-43538c80-8087-11e9-897d-5d212c41a482.png)

## Q2: How much would you be willing to lend per loan to an emerging market borrower?

![image](https://user-images.githubusercontent.com/518024/58418158-51091200-8087-11e9-88ce-e1005482a28c.png)

## Q3: What is the minimum interest rate you would be willing to lend for?

- Twitter data lost

## Q4: What is the maximum length of loan that you would lend your stablecoins at?

## Q5: Which stablecoins would you be willing to lend in?

![image](https://user-images.githubusercontent.com/518024/58418229-857cce00-8087-11e9-9755-129fb6c5eb42.png)

## Q6: Would you want to have a video interview with the borrower prior to lending?

![image](https://user-images.githubusercontent.com/518024/58418244-90cff980-8087-11e9-920a-cf1ceaf16f01.png)

## Q7: Would your confidence to lend be increased if potential borrowers were "vouched" by friends / families / colleagues? i.e. social credit

![image](https://user-images.githubusercontent.com/518024/58418294-b0672200-8087-11e9-9a75-04717eb502fa.png)

## Q8: (open ended) What kind of recourse would you want to have in case of late payments or defaults

## Q9: What advice would you have for us?

**Comment by onggunhao** [comment]
@tspoff @adibas03 Given the poll data, I think we should:

1. Go down the direction of a "Kiva" for DeFi type path - targeting lenders who are a "more forgiving market demographic" in terms of interest for our borrowers

2. Focus on making the experience good for micro-loans (i.e. <$100) as that is what most individual lenders are willing to lend

3. Build for Dai. It's clear that it's got an unsurmountable lead as the currency of DeFi.

4. I think Ines' 6% interest loan is still do-able, though I've got some doubts over whether there are 600 lenders willing to lend $100 at 6%. We may have to do a more rigorous demand experiment to test this.

5. We should add a "I want a video interview" to the sign up form, as 50% of potential lenders said they wanted a video interview

6. Since the majority of potential lenders were only willing to lend for 1 year, we should explore the use of a [Balloon Loan](https://www.investopedia.com/terms/b/balloonloan.asp). However, this opens Ines up to refinancing risk after 1 year, but also gives her more flexibility

**Comment by onggunhao** [comment]
Closing this issue - feedback incorporated into v2 wireframes.
